version: 2.1

jobs:
  build-e2e:
    docker:
      - image: cimg/openjdk:11.0.11-node
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install Tomcat
          command: |
            wget https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.18/bin/apache-tomcat-10.1.18.tar.gz
            tar xzvf apache-tomcat-10.1.18.tar.gz
            mv apache-tomcat-10.1.18 ~/tomcat

      - run:
          name: Build and Deploy WAR
          command: |
            mvn package
            cp target/*.war ~/tomcat/webapps/

      - run:
          name: Start Tomcat
          background: true
          command: ~/tomcat/bin/startup.sh

      - run:
          name: Run E2E Tests
          command: mvn verify

  unit-tests:
    docker:
      - image: cimg/openjdk:11.0.11-node
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: mvn test

  check-style:
    docker:
      - image: cimg/openjdk:11.0.11-node
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check

  deploy:
    docker:
      - image: cimg/openjdk:11.0.11-node
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install SSH Keys and SCP
          command: |
            apt-get update
            apt-get install -y sshpass
      - run:
          name: Transfer WAR to Server and Restart Tomcat
          command: |
            sshpass -p "your_vps_password" scp -o StrictHostKeyChecking=no target/*.war username@51.91.97.32:/path/to/tomcat/webapps/
            sshpass -p "your_vps_password" ssh -o StrictHostKeyChecking=no username@51.91.97.32 "sudo systemctl restart tomcat"

workflows:
  build-and-test:
    jobs:
      - unit-tests
      - check-style
      - build-e2e
      - deploy:
          requires:
            - build-e2e
