version: 2.1

jobs:
  build-e2e:
    docker:
      - image: cimg/openjdk:11.0.11-node
    working_directory: ~/project
    steps:
      - checkout

      # Installation de Tomcat
      - run:
          name: Install Tomcat
          command: |
            wget https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.18/bin/apache-tomcat-10.1.18.tar.gz
            tar xzvf apache-tomcat-10.1.18.tar.gz
            mv apache-tomcat-10.1.18 ~/tomcat

      # Construction du projet et copie du WAR dans Tomcat
      - run:
          name: Build and Deploy WAR
          command: |
            mvn package
            cp target/*.war ~/tomcat/webapps/

      # Démarrage de Tomcat
      - run:
          name: Start Tomcat
          background: true
          command: ~/tomcat/bin/startup.sh

      # Exécution des tests E2E
      - run:
          name: Run E2E Tests
          command: mvn verify

  unit-tests:
    docker:
      - image: cimg/openjdk:11.0.11-node
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: mvn test

  e2e-tests:
    docker:
      - image: cimg/openjdk:11.0.11-node
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Run E2E Tests
          command: mvn verify

workflows:
  build-and-test:
    jobs:
      - unit-tests
      - build-e2e
