version: 2.1
orbs:
  maven: circleci/maven@1.4.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0.392-node
    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Build with Maven
          command: mvn clean install

      - run:
          name: Run Tests
          command: mvn test

workflows:
  build-and-deploy:
    jobs:
      - build
